name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      # Install dependencies, then install HELICS from source
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libzmq5-dev libboost-dev
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install zeromq boost
      - uses: gmlc-tdc/helics-action/install@main
        id: helics-install
        with:
          version: 'v2'
          build_from_source: 'true'

      # Clone ns-3 and checkout this repository to the contrib subfolder
      - name: Clone latest ns-3
        run: |
          git clone --depth=1 https://gitlab.com/nsnam/ns-3-dev.git .
      - uses: actions/checkout@v2
        with:
          path: contrib/helics

      - name: Configure ns-3
        run: |
          ./ns3 configure --disable-werror --enable-examples --enable-tests | tee gha_waf_configure.log
          ! grep -Fq "HELICS not enabled" gha_waf_configure.log

      - name: Build ns-3
        run: ./ns3 build --jobs 6

